language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head

env:
  - "RAILS_VERSION=3.1.0"
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=master"

matrix:
  include:
    - rvm: 1.8.7
      env: "RAILS_VERSION=3.1.0"
    - rvm: 1.8.7
      env: "RAILS_VERSION=3.2.0"
    - rvm: 1.9.2
      env: "RAILS_VERSION=3.1.0"
    - rvm: 1.9.2
      env: "RAILS_VERSION=3.2.0"

  allow_failures:
    - rvm: ruby-head
    - env: "RAILS_VERSION=master"
